### PR TITLE
Fix indent-according-to-mode usage

### LINKED ISSUE #30: Problem with evil-sp-change indent-according-to-mode
## Bug

I have a strange (new-ish) issue. When using an operator such as `ce` in certain modes (so far, `markdown-mode` and `ledger-mode`), upon entering insert state, two unexpected things happen: a) the line indents up completely unindented, and b), the cursor is left at the beginning of the line.
## Trace

When I remove the call to `indent-according-to-mode` at the end of `evil-sp-change`, the issue no longer reproduces (of course, this isn't a solution).
## Examples

In `ledger-mode`, where `<P>` is the location of the point (the point being on the next letter):

```
2016/02/13 * Whole Foods                                                        
     Expenses:<P>Food:Groceries                   $49.93                            
     Liabilities:Credit:Citi 
```

When I `ce` at any point in that snippet (for example, on the `F` of `Food`), here's what happens:

```
2016/02/13 * Whole Foods                                                        
Expenses:<P>:Groceries                   $49.93                                    
     Liabilities:Credit:Andy:Citi
```

In `markdown-mode`:

```
## Net <P>profit                                                                   
```

Again, `ce`:

```
<P>## Net                                                                          
```
## Versions
- GNU Emacs 24.5.1 (x86_64-apple-darwin15.2.0) of 2015-12-19 on elcapitanvm.local, installed via Homebrew
- OS X El Capitan 10.11.3 (15D21)
- evil 20160312.1042
- evil-smartparens 20151126.124
- smartparens 20160225.705
- ledger-mode 20160228.1734
- markdown-mode 20160312.2335
## Minor modes

I have a lot of minor modes:

```
Enabled minor modes: Async-Bytecomp-Package Auto-Compile-On-Load                 
Auto-Compile-On-Save Auto-Composition Auto-Compression Auto-Encryption           
Company Company-Flx Dtrt-Indent Electric-Indent Evil Evil-Commentary             
Evil-Escape Evil-Local Evil-Matchit Evil-Smartparens Evil-Surround               
File-Name-Shadow Flx-Ido Flycheck Font-Lock Fortune-Cookie Git-Gutter            
Global-Auto-Revert Global-Company Global-Evil-Matchit                            
Global-Evil-Surround Global-Flycheck Global-Font-Lock                            
Global-Git-Commit Global-Git-Gutter Global-Undo-Tree                             
Global-Whitespace-Cleanup Ido-Grid Ido-Ubiquitous Line-Number Menu-Bar           
Override-Global Popwin Recentf Shell-Dirtrack Show-Smartparens                   
Show-Smartparens-Global Smartparens Smartparens-Global                           
Smartparens-Global-Strict Smartparens-Strict Tooltip Transient-Mark              
Undo-Tree Which-Key Whitespace-Cleanup Winner
```

But I've tested with and without `smartparens-strict-mode`, `smartparens-mode`, `electric-indent-mode`, `dtrt-indent-mode`, etc. It's `evil-smartparens`, but I bet it's interacting with something else odd (as there haven't been any changes to this package recently).

### PR DESCRIPTION
**Pull request by andyleejordan**
This fixes #30. In general we should not attempt to call this as it can have unexpected side-effects (like moving the point and shifting the whole-line when not desired).

This re-fixes #12 but without calling an indentation function.

The behavior is as close as I can get to what I think is desired in all the cases. However, there is a minor annoyance that `dd` and `cc` still move the point to the beginning of the line in the cases outlined in #12; however the indentation is unaffected. If we can fix that, I'd say this is perfect. Regardless, it's a major improvement on the current behavior.

This passed `make test`'s 38 tests. But please manually test edge cases to see if anything was missed, and it'd be awesome if I could get some help solving the point-move problem.

### CODE REVIEW

**Comment by expez** [comment]
Thanks for getting your hands dirty! 

I'll apply the patch manually and try it out for a few days to look for edge-cases.

**Comment by andyleejordan** [comment]
Thanks for dog-fooding @expez. Please do let me know if you figure out the cursor movement issue. I was debugging and it certainly appears to me that `dd` and `cc` move the cursor to the start of the line before `evil-sp-delete` and `evil-sp-change` are even called.

**Comment by andyleejordan** [comment]
@expez Any luck?

**Comment by expez** [comment]
Sorry about that @andschwa, I just put this in my `.emacs` and forgot about it :)  Atleast it's well-tested by now!

As to the cursor issue, I reached the same conclusion you did.  I don't want to reach into evil's internals so we'll just have to live with this, I think.

Thanks again! 👍

**Comment by andyleejordan** [comment]
Glad to hear it! Thanks for the merge :smile:

**Pull request merged**
