### PR TITLE
Keep bundled evil-tests.el of the load-path

### PR DESCRIPTION
**Pull request by tarsius**
Bundling a third-party library should generally be avoided because the
bundled version might end up being loaded for users who also have a
more recent version installed separately.

But because a user who wants to run the tests might not have `evil`'s
test file handy, it might make sense to bundle a copy anyway.  This
commit puts `evil-tests.el` in a separate directory which also
contains a file `.nosearch`, which ensures that it is not added to the
`load-path`.  The bundled library is still loaded, but only if the
upstream library cannot be found otherwise.

### CODE REVIEW

**Comment by expez** [comment]
Thank! 👍   This looks like a good idea to me.  Unfortunately this change caused the test suite to fail.

**Comment by tarsius** [comment]
I don't use `evil` myself but ran into this issue as part of my work on the Emacsmirror. And I haven't run the tests sorry. I suspect the issue is that the upstream `evil-tests.el` has changed and your tests are no longer compatible. In that case dropping `(or (require 'evil-tests)` would help. Or there is something wrong  with the below path manipulation. Could you post the output, please?

**Comment by expez** [comment]
Fixed and merged manually in https://github.com/expez/evil-smartparens/commit/7cde5544934930819e9dcaa1e0db2e3c58f0cd6f

In addition to fixing whatever issue you experienced over at Emacsmirror, this should make the package more friendly to those using a git module based setup.

Thanks @tarsius! 👍

**Comment by tarsius** [comment]
> this should make the package more friendly to those using a git module based setup.

Very noble of you! I'm one of those. If you are too, then you might want to give my [`borg`](https://emacsmirror.net/manual/borg/) package manager a try.

**Pull request closed without merging**
